[workspace]
channels = ["conda-forge"]
name = "jingleplayer"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.3,<3.14"
jsonschema = ">=4.23.0,<5"
humanize = ">=4.12.3,<5"
pynput = ">=1.8.1,<2"

[pypi-dependencies]
tinytag = ">=2.0.0"
pytimeparse2 = ">=1.7.1, <2"
playsound3 = ">=3.2.4, <4"
pause = ">=0.3, <0.4"

[target.linux-64.pypi-dependencies]
sdbus = ">=0.14.0,<0.15"

[feature.lint.dependencies]
ruff = ">=0.11.11"

[environments]
dev = ["lint"]

[tasks]
debugconfig = "python -m jingleplayer \"./tournaments/example/config - for testing.json\" --logfile ./test.log --loglevel debug -p dummy"
